###조직정보 등록
POST localhost:8080/department-members
Content-Type: application/json

{
  "employeeNumber": 2020,
  "departmentCode": "L1001"
}

###조직정보 조회
GET localhost:8080/department-members/L1001
Content-Type: application/json